### ISSUE TITLE
Tool 'test' failed with Command *** returned non-zero exit status 1, whereas running the single test returns 0

### ISSUE THREAD

**Issue by gigianni** [kalhauge/jpamb#11]
When I run evaluate.py I get errors for each tool runned
![image](https://github.com/user-attachments/assets/88b2a5dc-4338-4e12-9146-1c6ac13215eb)
whereas if the single test is runned everything looks fine.
![image](https://github.com/user-attachments/assets/fff3a967-7eeb-4891-9cf5-dd97277465b2)

Is there a way to get the output of each run from evaluate.py?

**Comment by kalhauge** [comment]
Hi you should not run your interpreter using the `bin/evaluate.py` tool, instead use the `bin/test.py` tool. 

I hope this fix the problem, otherwise please use a lot of `-v`s so that we can get as much debugging as possible.

**Comment by kalhauge** [comment]
If it did not fix the problem fell free to reopen the issue! :)
