### ISSUE TITLE
KeyError in the new array tests?

### ISSUE THREAD

**Issue by jayveedee** [kalhauge/jpamb#12]
Attached some images of the error from the golden.log

![image](https://github.com/user-attachments/assets/ed625b64-24c2-46dc-9622-d048f93ee5f9)
![image](https://github.com/user-attachments/assets/ee3caf52-19b4-4c0a-9807-46633de95fc8)

Seems like something happens when trying to run the cases with arrays as inputs. I also looked at the cases.txt and distribution.csv and saw that the parameter for the arrays were missing the right bracket: "]". Tried fixing that but got another error instead. See images

![image](https://github.com/user-attachments/assets/fa97ba6f-4d4e-4651-9dad-6cb1e1809392)

![image](https://github.com/user-attachments/assets/38cffddf-2b45-4709-b357-99b8812be95c)

![image](https://github.com/user-attachments/assets/2a8b4974-483a-4c1f-b1d2-4acdb022c9f5)

The cases annotations in Arrays.java look fine however

![image](https://github.com/user-attachments/assets/a713a339-eca0-4cc5-a9b3-7c8b67f44597)

This happened on my machine (Windows 11) and my group mates' machines (Mac/WIndows)

**Comment by kalhauge** [comment]
Hi! 

The format for input and input types has evolved a bit to allow for arrays, please take a look at: https://github.com/kalhauge/jpamb/blob/72d82bb5484da052a1332fcdc8815e85da69a293/jpamb_utils/__init__.py#L59-L74 and https://github.com/kalhauge/jpamb/blob/72d82bb5484da052a1332fcdc8815e85da69a293/jpamb_utils/__init__.py#L218 for a reference for both.

**Comment by kalhauge** [comment]
But I also consider this a documentation issue as the README should state the format more clearly. Sorry about that.

**Comment by jayveedee** [comment]
What can I do to fix the issue with the KeyError then? Are the case annotations incorrect then if "[I" is correct?

**Comment by kalhauge** [comment]
I see that the bug is in your interpreter at line 43. I can't do anything to fix it. But instead of using your own MethodId you can use the one in the jpamb_utils.

**Comment by jayveedee** [comment]
Oh, I think why we're getting this error. We haven't gotten the new changes for the interpreter.py that have been added to your repo. I will fix this and close the issue if it's resolved. Thanks for the help :)
